### ISSUE TITLE
Crash on lolipop

### ISSUE THREAD

**Issue by thomasuster** [thomasuster/android-expansion#1]
`
E/AndroidRuntime(14297): FATAL EXCEPTION: main
E/AndroidRuntime(14297): Process: com.protogames.develop.pakkapets, PID: 14297
E/AndroidRuntime(14297): java.lang.IllegalArgumentException: Service Intent must be explicit: Intent { act=com.android.vending.licensing.ILicensingService }
E/AndroidRuntime(14297):    at android.app.ContextImpl.validateServiceIntent(ContextImpl.java:1745)
E/AndroidRuntime(14297):    at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1844)
E/AndroidRuntime(14297):    at android.app.ContextImpl.bindService(ContextImpl.java:1822)
E/AndroidRuntime(14297):    at android.content.ContextWrapper.bindService(ContextWrapper.java:538)
E/AndroidRuntime(14297):    at com.google.android.vending.licensing.LicenseChecker.checkAccess(LicenseChecker.java:150)
E/AndroidRuntime(14297):    at com.google.android.vending.expansion.downloader.impl.DownloaderService$LVLRunnable.run(DownloaderService.java:768)
E/AndroidRuntime(14297):    at android.os.Handler.handleCallback(Handler.java:739)
E/AndroidRuntime(14297):    at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime(14297):    at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime(14297):    at android.app.ActivityThread.main(ActivityThread.java:5272)
E/AndroidRuntime(14297):    at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(14297):    at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime(14297):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:909)
E/AndroidRuntime(14297):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:704)
`
http://stackoverflow.com/questions/28305125/android-app-crashes-on-lollipop

**Comment by thomasuster** [comment]
Don't let me forget @ousado
